In [45]:
import numpy as np

In [46]:
#Q.1 Write a NumPy program to create a 5×5 matrix with values 1,2,3,…,25.
matrix = np.arange(1,26).reshape(5,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [47]:
#Q.2 Generate a 4×4 identity matrix using NumPy.
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
#Q.3 Create a 1D array of numbers from 100 to 200 with step size 10.
array_1d = np.arange(100, 201, 10)
print(array_1d)

[100 110 120 130 140 150 160 170 180 190 200]


In [49]:
#Q.4 Generate a random 3×3 matrix and find its determinant.
matrix_3x3 = np.random.randint(size=(3, 3), low=1, high=10)
determinant = np.linalg.det(matrix_3x3)
print("Random 3x3 Matrix:")
print(matrix_3x3)
print("Determinant:")
print(determinant)

Random 3x3 Matrix:
[[2 1 5]
 [3 7 5]
 [3 1 6]]
Determinant:
-19.000000000000014


In [50]:
# Q.5 Create a NumPy array of 10 random integers between 1 and 100. 
random_integers = np.random.randint(1, 101, size=10)
print(random_integers)

[10 81 57 97  2  1 63 22 17 88]


In [51]:
# Q.6 Write a program to reshape a 1D array of size 12 into a 3×4 matrix.
array_1d = np.arange(1,13)
array_reshaped = array_1d.reshape(3,4)
print(array_reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
#Q.7 Create two 3×3 matrices and perform matrix multiplication.

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
# matrix_multiplication = np.dot(a,b)
# matrix_multiplication = a @ b
matrix_multiplication = np.matmul(a,b)
print(matrix_multiplication)


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [53]:
# Q.8 Find eigenvalues and eigenvectors of a given 2×2 matrix using NumPy.
matrix_2x2 = np.arange(1,5).reshape(2,2)
eigenvalues, eigenvectors = np.linalg.eig(matrix_2x2)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [54]:
#Q.9 Create a 5×5 matrix with random values and extract its diagonal elements.
random_matrix = np.random.rand(5, 5)
diagonal_elements = np.diagonal(random_matrix)
print("Random Matrix:")
print(random_matrix)
print("Diagonal Elements:")
print(diagonal_elements)

Random Matrix:
[[0.06288882 0.7908418  0.81274774 0.00809558 0.55040091]
 [0.20511805 0.70874508 0.29551754 0.13261442 0.73935214]
 [0.73866902 0.94310511 0.56005428 0.33878703 0.3107149 ]
 [0.93938378 0.90796565 0.35613017 0.4895837  0.23639497]
 [0.26181346 0.4525902  0.07131536 0.40404222 0.23961921]]
Diagonal Elements:
[0.06288882 0.70874508 0.56005428 0.4895837  0.23961921]


In [55]:
# Q.10 Generate a 1D array and normalize it (scale values between 0 and 1).
# array_1d = np.random.randint(1, 101, size=10)
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# normalized_array = [(array_1d_ele - np.min(array_1d)) / (np.max(array_1d) - np.min(array_1d)) for array_1d_ele in array_1d]
normalized_array = (array_1d - np.min(array_1d)) / (np.max(array_1d) - np.min(array_1d))
print("Original Array:")
print(array_1d) 
print("Normalized Array:")
print(normalized_array)

Original Array:
[ 10  20  30  40  50  60  70  80  90 100]
Normalized Array:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [56]:
#Q.11 Write a program to sort a NumPy array by row and column.
array_2d = np.random.randint(1, 101, size=(4,4))
sorted_by_row = np.sort(array_2d, axis=1)
sorted_by_column = np.sort(array_2d, axis=0)
print("Original Array:")
print(array_2d)
print("Sorted by Row:")
print(sorted_by_row)
print("Sorted by Column:")
print(sorted_by_column)

Original Array:
[[47 25 56 91]
 [27 83 35  2]
 [12 90  8 28]
 [57 41 80 98]]
Sorted by Row:
[[25 47 56 91]
 [ 2 27 35 83]
 [ 8 12 28 90]
 [41 57 80 98]]
Sorted by Column:
[[12 25  8  2]
 [27 41 35 28]
 [47 83 56 91]
 [57 90 80 98]]


In [57]:
#Q.12 Find the indices of maximum and minimum values in a NumPy array.
array_1d = np.random.randint(1, 101, size=10)
max_index = np.argmax(array_1d)
min_index = np.argmin(array_1d)
print("Array:")
print(array_1d)
print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)


Array:
[ 1 96 33 74 73 61 79 97 72 41]
Index of Maximum Value: 7
Index of Minimum Value: 0


In [58]:
#Q.13 Create a 2D array and flatten it using ravel() and flatten().
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_ravel = array_2d.ravel()
flattened_flatten = array_2d.flatten()
print("Original Array:")
print(array_2d)
print("Flattened using ravel():")
print(flattened_ravel)
print("Flattened using flatten():")
print(flattened_flatten)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened using ravel():
[1 2 3 4 5 6 7 8 9]
Flattened using flatten():
[1 2 3 4 5 6 7 8 9]


In [59]:
#Q.14 Create a 3×3 matrix and compute its inverse using NumPy.
matrix_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse_matrix = np.linalg.inv(matrix_3x3)
print("Original Matrix:")
print(matrix_3x3)
print("Inverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse Matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [60]:
#Q.15 Write a NumPy program to generate a random permutation of numbers 1 to 10.
permutation = np.random.permutation(np.arange(1, 11))
print("Random Permutation:")
print(permutation)

Random Permutation:
[ 8  9  4 10  5  6  3  2  1  7]


In [61]:
#Q.16 Create a NumPy array with values from 0 to 20 and replace all even numbers with -1.
array_1d = np.arange(21)
array_1d[array_1d % 2 == 0] = -1
print("Modified Array:")
print(array_1d)

Modified Array:
[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [62]:
#Q.17 Write a program to compute the dot product of two arrays.
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
dot_product = np.dot(array1, array2)
print("Dot Product:")
print(dot_product)


Dot Product:
32


In [63]:
#Q.18 Generate a 5×5 random matrix and compute its trace.
matrix_5x5 = np.random.rand(5, 5)
trace = np.trace(matrix_5x5)
print("Original Matrix:")
print(matrix_5x5)
print("Trace of the Matrix:")
print(trace)

Original Matrix:
[[0.02208355 0.21202634 0.61027191 0.90052902 0.51304205]
 [0.25844075 0.88270619 0.411113   0.77746907 0.54706801]
 [0.71246378 0.05536546 0.61234492 0.38495851 0.99121414]
 [0.38586727 0.7483853  0.62470536 0.76203838 0.06042936]
 [0.16715325 0.29107525 0.32028792 0.48846862 0.21748136]]
Trace of the Matrix:
2.4966543953004923


In [87]:
#Q.19 Write a NumPy program to split a 1D array into 3 equal parts.
arr= np.arange(9)
part1, part2, part3 = np.array_split(arr, 3)
print("Original Array:")
print(arr)
print("Split Arrays:")
print(part1)
print(part2)
print(part3)

Original Array:
[0 1 2 3 4 5 6 7 8]
Split Arrays:
[0 1 2]
[3 4 5]
[6 7 8]


In [88]:
#Q.20 Create a 3D array of shape (3,3,3) and find its mean across axis=0.
array_3d = np.random.rand(3, 3, 3)
mean_axis0 = np.mean(array_3d, axis=0)
print("Original 3D Array:")
print(array_3d)
print("Mean across axis 0:")
print(mean_axis0)

Original 3D Array:
[[[0.5054347  0.47838799 0.02206673]
  [0.8071434  0.05366213 0.42790774]
  [0.90014603 0.60402552 0.35935244]]

 [[0.38862511 0.45891712 0.3307652 ]
  [0.90872603 0.15652448 0.0820638 ]
  [0.72883389 0.90478893 0.73121502]]

 [[0.97159536 0.82852876 0.07649119]
  [0.58330358 0.45132976 0.34687226]
  [0.12748256 0.23557811 0.83002807]]]
Mean across axis 0:
[[0.62188506 0.58861129 0.14310771]
 [0.766391   0.22050545 0.2856146 ]
 [0.58548749 0.58146419 0.64019851]]


In [89]:
#Q.21 Write a program to find the cumulative sum of a NumPy array.
arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)
print("Original Array:")
print(arr)
print("Cumulative Sum:")
print(cumulative_sum)

Original Array:
[1 2 3 4 5]
Cumulative Sum:
[ 1  3  6 10 15]


In [90]:
#Q.22 Create a 4×4 matrix with random integers and extract its upper triangular matrix.
matrix_4x4 = np.random.randint(1, 101, size=(4,4))
upper_triangular = np.triu(matrix_4x4)
print("Original 4x4 Matrix:")
print(matrix_4x4)
print("Upper Triangular Matrix:")
print(upper_triangular)

Original 4x4 Matrix:
[[51 13 70 75]
 [83 89 20 61]
 [37 37 75 76]
 [28 52 22 60]]
Upper Triangular Matrix:
[[51 13 70 75]
 [ 0 89 20 61]
 [ 0  0 75 76]
 [ 0  0  0 60]]


In [91]:
#Q.23 Write a program to generate a matrix of size 6×6 with checkerboard pattern (0,1).
checkerboard = np.zeros((6,6), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:")
print(checkerboard)

Checkerboard Pattern:
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [92]:
#Q.24 Generate a 3×3 random matrix and apply element-wise square root.
matrix_3x3 = np.random.rand(3, 3)
elementwise_sqrt = np.sqrt(matrix_3x3)
print("Original 3x3 Matrix:")
print(matrix_3x3)
print("Element-wise Square Root:")
print(elementwise_sqrt)

Original 3x3 Matrix:
[[0.95799607 0.18170204 0.57421873]
 [0.22305098 0.41138129 0.14850933]
 [0.9797537  0.76732418 0.68385779]]
Element-wise Square Root:
[[0.97877274 0.42626522 0.75777221]
 [0.47228273 0.64139013 0.38536908]
 [0.98982509 0.87597042 0.82695694]]


In [93]:
#Q.25 Create a 1D array of 20 elements and reverse it without using Python slicing.
arr = np.arange(20)
reversed_arr = np.flip(arr)
print("Original Array:")
print(arr)
print("Reversed Array:")
print(reversed_arr)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reversed Array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [94]:

#Q.26 Write a program to merge two NumPy arrays vertically and horizontally.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
vertical_merge = np.vstack((array1, array2))
horizontal_merge = np.hstack((array1, array2))
print("Vertical Merge:")
print(vertical_merge)
print("Horizontal Merge:")
print(horizontal_merge)

Vertical Merge:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Merge:
[[1 2 5 6]
 [3 4 7 8]]


In [95]:
#Q.27 Create a 2D NumPy array and compute row-wise and column-wise sum.
matrix_2d = np.random.randint(1, 101, size=(5, 5))
row_wise_sum = np.sum(matrix_2d, axis=1)
column_wise_sum = np.sum(matrix_2d, axis=0)
print("Original 2D Matrix:")
print(matrix_2d)
print("Row-wise Sum:")
print(row_wise_sum)
print("Column-wise Sum:")
print(column_wise_sum)

Original 2D Matrix:
[[14  4  1  2 91]
 [37 68 65 83 28]
 [79 76 49 55 32]
 [65 38 91  3 27]
 [58 19 72 60 57]]
Row-wise Sum:
[112 281 291 224 266]
Column-wise Sum:
[253 205 278 203 235]


In [96]:

#Q.28 Write a NumPy program to replace NaN values in an array with the mean of that column.
matrix_with_nan = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_mean = np.nanmean(matrix_with_nan, axis=0)
indices = np.where(np.isnan(matrix_with_nan))
matrix_with_nan[indices] = np.take(col_mean, indices[1])
print("Matrix after replacing NaN values:")
print(matrix_with_nan)

Matrix after replacing NaN values:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [98]:

#Q.29 Generate two 1D arrays and compute cosine similarity using NumPy.
array1 = np.random.rand(10)
array2 = np.random.rand(10)
cosine_similarity = np.dot(array1, array2) / (np.linalg.norm(array1) * np.linalg.norm(array2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Cosine Similarity:")
print(cosine_similarity)

Array 1:
[0.36311919 0.71313025 0.55469508 0.39804131 0.92754964 0.28575719
 0.65770167 0.20409506 0.69750106 0.48589433]
Array 2:
[0.53906567 0.29532336 0.23425938 0.12816577 0.61159668 0.75412539
 0.64634966 0.94931862 0.3436246  0.931419  ]
Cosine Similarity:
0.7741118064241872


In [99]:
#Q.30 Create a 4×4 array and rotate it by 90 degrees using NumPy.
matrix_4x4 = np.random.rand(4, 4)
rotated_matrix = np.rot90(matrix_4x4)
print("Original 4x4 Matrix:")
print(matrix_4x4)
print("Rotated 90 Degrees:")
print(rotated_matrix)

Original 4x4 Matrix:
[[0.43524195 0.51698178 0.15543549 0.59643996]
 [0.8014096  0.72728465 0.28367425 0.90351368]
 [0.66660768 0.13787227 0.51858616 0.40856279]
 [0.05900883 0.38818444 0.36167098 0.0536087 ]]
Rotated 90 Degrees:
[[0.59643996 0.90351368 0.40856279 0.0536087 ]
 [0.15543549 0.28367425 0.51858616 0.36167098]
 [0.51698178 0.72728465 0.13787227 0.38818444]
 [0.43524195 0.8014096  0.66660768 0.05900883]]


In [100]:
#Q.31 Write a program to create a structured NumPy array with fields (name, age, marks).
dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('marks', 'f4')])
structured_array = np.array([('Alice', 20, 85.5), ('Bob', 21, 90.0), ('Charlie', 19, 88.0)], dtype=dtype)
print("Structured NumPy Array:")
print(structured_array)

Structured NumPy Array:
[('Alice', 20, 85.5) ('Bob', 21, 90. ) ('Charlie', 19, 88. )]


In [101]:
#Q.32 Generate a random 3×3 matrix and compute its rank.
matrix_3x3 = np.random.rand(3, 3)
matrix_rank = np.linalg.matrix_rank(matrix_3x3)
print("Original 3x3 Matrix:")
print(matrix_3x3)
print("Rank of the Matrix:")
print(matrix_rank)

Original 3x3 Matrix:
[[0.50841344 0.1348567  0.67239522]
 [0.3429596  0.70235254 0.29867445]
 [0.51785226 0.96989572 0.96478598]]
Rank of the Matrix:
3


In [102]:
#Q.33 Create a 5×5 random matrix and normalize each row to have unit length.
matrix_5x5 = np.random.rand(5, 5)
row_norms = np.linalg.norm(matrix_5x5, axis=1, keepdims=True)
normalized_matrix = matrix_5x5 / row_norms
print("Original 5x5 Matrix:")
print(matrix_5x5)
print("Normalized 5x5 Matrix:")
print(normalized_matrix)


Original 5x5 Matrix:
[[0.80194388 0.68778845 0.79105353 0.47429412 0.04912281]
 [0.71659593 0.62347258 0.42917858 0.58443268 0.07823715]
 [0.94772703 0.30551635 0.79835448 0.25280409 0.01709728]
 [0.7757213  0.04822147 0.36920839 0.7401567  0.19509335]
 [0.11867673 0.66856045 0.60659237 0.00917575 0.46769485]]
Normalized 5x5 Matrix:
[[0.57146281 0.49011599 0.56370238 0.33798057 0.03500477]
 [0.59838943 0.5206273  0.35838318 0.48802725 0.06533149]
 [0.72835333 0.23479741 0.61355656 0.19428664 0.01313971]
 [0.67357908 0.04187196 0.32059329 0.64269741 0.16940465]
 [0.11593626 0.65312212 0.592585   0.00896387 0.45689489]]


In [103]:
#Q.34 Write a NumPy program to check whether two arrays are equal element-wise.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(array1, array2)
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Are the two arrays equal?")
print(are_equal)

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[1 2]
 [3 4]]
Are the two arrays equal?
True


In [106]:

#Q.35 Generate a random dataset of 1000 numbers and compute histogram using NumPy. 
data = np.random.randn(1000)
hist, bin_edges = np.histogram(data, bins=30)
print("Histogram:")
print(hist)
print("Bin Edges:")
print(bin_edges)

Histogram:
[ 1  4  0  8  3 15 26 27 31 48 50 60 74 89 72 73 84 67 52 52 47 33 30 18
 15 11  5  4  0  1]
Bin Edges:
[-3.0881045  -2.88473998 -2.68137545 -2.47801093 -2.2746464  -2.07128188
 -1.86791735 -1.66455283 -1.4611883  -1.25782378 -1.05445925 -0.85109473
 -0.6477302  -0.44436568 -0.24100115 -0.03763663  0.1657279   0.36909242
  0.57245694  0.77582147  0.97918599  1.18255052  1.38591504  1.58927957
  1.79264409  1.99600862  2.19937314  2.40273767  2.60610219  2.80946672
  3.01283124]


In [107]:
#Q.36 Create a 2D array and apply broadcasting to add a 1D array.
array_2d = np.random.rand(4, 3)
array_1d = np.random.rand(3)
result = array_2d + array_1d
print("Original 2D Array:")
print(array_2d)
print("1D Array:")
print(array_1d)
print("Result after Broadcasting:")
print(result)

Original 2D Array:
[[0.76248388 0.96195759 0.06695861]
 [0.12180572 0.17919023 0.61575679]
 [0.10924383 0.44119969 0.55005741]
 [0.35886006 0.44019018 0.05224339]]
1D Array:
[0.84373031 0.76869809 0.46091717]
Result after Broadcasting:
[[1.60621419 1.73065568 0.52787578]
 [0.96553604 0.94788832 1.07667397]
 [0.95297414 1.20989778 1.01097459]
 [1.20259037 1.20888827 0.51316057]]


In [110]:
#Q.37 Write a program to find unique values and their counts in a NumPy array.
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique, counts = np.unique(array, return_counts=True)
print("Unique Values:")
print(unique)
print("Counts:")
print(counts)

Unique Values:
[1 2 3 4 5]
Counts:
[1 2 1 3 1]


In [112]:
#Q.38 Create two arrays and find Pearson correlation coefficient using NumPy.
array_x = np.random.randn(100)
array_y = np.random.randn(100)
correlation_coefficient = np.corrcoef(array_x, array_y)[0, 1]
print("Array X:")
print(array_x)
print("Array Y:")
print(array_y)
print("Pearson Correlation Coefficient:")
print(correlation_coefficient)

Array X:
[-1.42357983  0.05854224 -1.23483159  0.16546589 -0.35012089 -0.17074581
  0.28648015  0.10138857 -1.76993704 -1.44342396 -0.14830246 -0.32936769
  1.6725953   1.26566382  0.84840127  0.75768585  0.17662619  0.21024256
 -0.53509062  1.70966311 -0.00361668 -1.27838623  0.41417207 -0.07728157
  0.34770406  0.83919638  1.12659509  1.92692858 -2.3343444  -0.18391676
 -0.78348606 -0.42550944 -0.88984791 -0.54819005  0.33745824 -2.41297242
 -0.21820439  1.25136679 -1.60232548 -0.43951674 -0.20582616  1.54452285
 -0.57568023 -0.91864137  1.5698907   0.68313695 -0.22447464 -0.49311858
 -0.90581524  0.13111648  0.63266    -0.57509033 -0.65872744  0.58156357
 -0.99036073  1.21249828  1.11391304  2.30010737 -1.06231287 -1.20708586
  0.95964557  1.6140024   0.53336481 -0.97105845 -0.76440431  1.50181912
  0.79906231 -1.4625766   0.46266599 -1.35088923 -0.88550321  0.22573954
  1.86050084  2.00690996 -0.94734502 -0.47495299 -1.03651356 -0.93447912
  0.11725389 -0.05059686 -0.31098274  0.76

In [113]:
#Q.39 Write a NumPy program to compute numerical gradient of a 1D array.
array = np.array([1, 2, 3, 4, 5])
gradient = np.gradient(array)
print("Original Array:")
print(array)
print("Numerical Gradient:")
print(gradient)

Original Array:
[1 2 3 4 5]
Numerical Gradient:
[1. 1. 1. 1. 1.]


In [115]:
#Q.40 Generate a random 3×3 matrix and perform Singular Value Decomposition (SVD).
matrix_3x3 = np.random.rand(3, 3)
U, S, VT = np.linalg.svd(matrix_3x3)
print("Original 3x3 Matrix:")
print(matrix_3x3)
print("U Matrix:")
print(U)
print("Singular Values:")
print(S)
print("VT Matrix:")
print(VT)

Original 3x3 Matrix:
[[0.77844867 0.96161224 0.57739092]
 [0.51413477 0.78745149 0.52429542]
 [0.27429445 0.29727981 0.46848549]]
U Matrix:
[[-0.74454585  0.38486635  0.54546253]
 [-0.58762226  0.00989517 -0.80907488]
 [-0.31678314 -0.92291927  0.21878863]]
Singular Values:
[1.82867417 0.2353377  0.08378034]
VT Matrix:
[[-0.52967316 -0.69605711 -0.48471728]
 [ 0.21898112  0.43987384 -0.87095251]
 [ 0.81944714 -0.5674641  -0.080566  ]]
